# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.FileField(upload_to='')),
                ('descr', models.CharField(default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('descr', models.CharField(default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standalone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default=None, max_length=40)),
                ('machine_type', models.CharField(default=7781, max_length=30, null=True)),
                ('descr', models.CharField(default=None, max_length=300, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logstat.Source')),
            ],
        ),
        migrations.AddField(
            model_name='attach',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logstat.Standalone'),
        ),
    ]
