# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0002_mattach'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattach',
            name='matt',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='attach',
            name='att',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
