# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0005_attach_thumbnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmldescr', models.CharField(default=None, max_length=300, null=True)),
                ('xmlatt', models.FileField(null=True, upload_to='')),
                ('xml_added_date', models.DateField()),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logstat.Standalone')),
            ],
        ),
    ]
