# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0007_auto_20171125_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlatt',
            name='xml_added_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 15, 59, 14, 703626, tzinfo=utc)),
        ),
    ]
