# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0012_auto_20171125_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standalone',
            name='serial',
        ),
        migrations.AddField(
            model_name='standalone',
            name='origfilename',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='xmlatt',
            name='xml_added_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 5, 54, 44, 811736, tzinfo=utc)),
        ),
    ]
