# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0013_auto_20171126_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standalone',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='standalone',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 7, 42, 42, 912098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='xmlatt',
            name='xml_added_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 7, 42, 42, 913598, tzinfo=utc)),
        ),
    ]
