# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0016_auto_20171126_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standalone',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 9, 8, 18, 358060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='standalone',
            name='origfilename',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='xmlatt',
            name='xml_added_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 9, 8, 18, 360060, tzinfo=utc)),
        ),
    ]
