# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0017_auto_20171126_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlatt',
            name='xmldescr',
        ),
        migrations.AlterField(
            model_name='standalone',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 6, 48, 28, 722711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='xmlatt',
            name='xml_added_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 27, 6, 48, 28, 724211, tzinfo=utc)),
        ),
    ]
