# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0018_auto_20171203_1954'),
        ('logstat', '0018_auto_20171127_0848'),
    ]

    operations = [
    ]
