# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logstat', '0019_merge_20171205_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlatt',
            name='xmldescr',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='standalone',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 11, 41, 7, 483747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='xmlatt',
            name='xml_added_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 11, 41, 7, 485747, tzinfo=utc)),
        ),
    ]
